name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  mix_check:
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ['25.x', '24.x', '23.x']
        elixir: ['1.14.x', '1.13.x']
        include:
          - otp: '24.x'
            elixir: '1.12.x'
          - otp: '23.x'
            elixir: '1.12.x'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix
    - name: Install dependencies
      run: mix deps.get
    - name: Run mix check
      run: mix check
